name: main
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache foo
        uses: n0izn0iz/mkache@v3.0.10
        with:
          rule: foo
          key: foo

      - name: Make foo
        run: make foo