name: main
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            trigger:
              - "!**/no-trigger/**"

      - name: Cache foo
        id: cache
        if: steps.changes.outputs.trigger == 'true'
        uses: actions/cache@v2.1.6
        with:
          path: foo
          key: foo-${{ github.ref }}-${{ github.sha }}
          restore-keys: foo-refs/heads/master-

      - name: Debug
        run: echo ${{ steps.cache.outputs.cache-hit }}

      - name: Touch foo
        if: steps.cache.outputs.cache-hit == 'true'
        run: touch foo
      
      - name: Make foo
        run: make foo